-- 000007 宠物模式：宠物养成 + 投喂 + 好感度

CREATE TABLE IF NOT EXISTS pets (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  child_id BIGINT NOT NULL,
  name VARCHAR(64) NOT NULL DEFAULT '小星球',
  species VARCHAR(32) NOT NULL DEFAULT 'cat',
  level INT NOT NULL DEFAULT 1,
  exp INT NOT NULL DEFAULT 0,
  hunger INT NOT NULL DEFAULT 80,
  affection INT NOT NULL DEFAULT 20,
  fed_count INT NOT NULL DEFAULT 0,
  last_fed_at TIMESTAMP NULL,
  last_decay_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pets_child (child_id)
);
