-- 补加食物库存列（兼容 000008_pet_food_inventory 被同版本号跳过的情况）
-- 使用 IF NOT EXISTS 确保 MySQL 8.0+ 上重复执行安全
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_apple INT NOT NULL DEFAULT 0;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_fish INT NOT NULL DEFAULT 0;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_milk INT NOT NULL DEFAULT 0;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_star INT NOT NULL DEFAULT 0;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_cake INT NOT NULL DEFAULT 0;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_hotpot INT NOT NULL DEFAULT 0;
-- 记录已花费的星星数（用于星星兑换零食）
ALTER TABLE pets ADD COLUMN IF NOT EXISTS stars_spent INT NOT NULL DEFAULT 0;