-- 000008 宠物食物库存：投喂改为有限数量，初始为0；积分/星星惩罚由业务层实现
ALTER TABLE pets ADD COLUMN food_apple INT NOT NULL DEFAULT 0,
 ADD COLUMN food_fish INT NOT NULL DEFAULT 0,
 ADD COLUMN food_milk INT NOT NULL DEFAULT 0,
 ADD COLUMN food_star INT NOT NULL DEFAULT 0,
 ADD COLUMN food_cake INT NOT NULL DEFAULT 0,
 ADD COLUMN food_hotpot INT NOT NULL DEFAULT 0;