// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package studyplanet

import (
	"studyplanet/api/studyplanet"
)

type ControllerV1 struct{}

func NewV1() studyplanet.IStudyplanetV1 {
	return &ControllerV1{}
}
