// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalChildrenDao is an internal type for wrapping the internal DAO implementation.
type internalChildrenDao = *internal.ChildrenDao

// childrenDao is the data access object for the table children.
// You can define custom methods on it to extend its functionality as needed.
type childrenDao struct {
	internalChildrenDao
}

var (
	// Children is a globally accessible object for table children operations.
	Children = childrenDao{
		internal.NewChildrenDao(),
	}
)

// Add your custom methods and functionality below.
