// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// leaderboardWeeklyDao is the data access object for the table leaderboard_weekly.
// You can define custom methods on it to extend its functionality as needed.
type leaderboardWeeklyDao struct {
	*internal.LeaderboardWeeklyDao
}

var (
	// LeaderboardWeekly is a globally accessible object for table leaderboard_weekly operations.
	LeaderboardWeekly = leaderboardWeeklyDao{internal.NewLeaderboardWeeklyDao()}
)

// Add your custom methods and functionality below.
