// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalMathProblemsDao is an internal type for wrapping the internal DAO implementation.
type internalMathProblemsDao = *internal.MathProblemsDao

// mathProblemsDao is the data access object for the table math_problems.
// You can define custom methods on it to extend its functionality as needed.
type mathProblemsDao struct {
	internalMathProblemsDao
}

var (
	// MathProblems is a globally accessible object for table math_problems operations.
	MathProblems = mathProblemsDao{
		internal.NewMathProblemsDao(),
	}
)

// Add your custom methods and functionality below.
