// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalParentsDao is an internal type for wrapping the internal DAO implementation.
type internalParentsDao = *internal.ParentsDao

// parentsDao is the data access object for the table parents.
// You can define custom methods on it to extend its functionality as needed.
type parentsDao struct {
	internalParentsDao
}

var (
	// Parents is a globally accessible object for table parents operations.
	Parents = parentsDao{
		internal.NewParentsDao(),
	}
)

// Add your custom methods and functionality below.
