// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalPointsLogDao is an internal type for wrapping the internal DAO implementation.
type internalPointsLogDao = *internal.PointsLogDao

// pointsLogDao is the data access object for the table points_log.
// You can define custom methods on it to extend its functionality as needed.
type pointsLogDao struct {
	internalPointsLogDao
}

var (
	// PointsLog is a globally accessible object for table points_log operations.
	PointsLog = pointsLogDao{
		internal.NewPointsLogDao(),
	}
)

// Add your custom methods and functionality below.
