// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalPracticeSessionsDao is an internal type for wrapping the internal DAO implementation.
type internalPracticeSessionsDao = *internal.PracticeSessionsDao

// practiceSessionsDao is the data access object for the table practice_sessions.
// You can define custom methods on it to extend its functionality as needed.
type practiceSessionsDao struct {
	internalPracticeSessionsDao
}

var (
	// PracticeSessions is a globally accessible object for table practice_sessions operations.
	PracticeSessions = practiceSessionsDao{
		internal.NewPracticeSessionsDao(),
	}
)

// Add your custom methods and functionality below.
