// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalReadingsDao is an internal type for wrapping the internal DAO implementation.
type internalReadingsDao = *internal.ReadingsDao

// readingsDao is the data access object for the table readings.
// You can define custom methods on it to extend its functionality as needed.
type readingsDao struct {
	internalReadingsDao
}

var (
	// Readings is a globally accessible object for table readings operations.
	Readings = readingsDao{
		internal.NewReadingsDao(),
	}
)

// Add your custom methods and functionality below.
