// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalReadingQuestionsDao is an internal type for wrapping the internal DAO implementation.
type internalReadingQuestionsDao = *internal.ReadingQuestionsDao

// readingQuestionsDao is the data access object for the table reading_questions.
// You can define custom methods on it to extend its functionality as needed.
type readingQuestionsDao struct {
	internalReadingQuestionsDao
}

var (
	// ReadingQuestions is a globally accessible object for table reading_questions operations.
	ReadingQuestions = readingQuestionsDao{
		internal.NewReadingQuestionsDao(),
	}
)

// Add your custom methods and functionality below.
