// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalRedemptionsDao is an internal type for wrapping the internal DAO implementation.
type internalRedemptionsDao = *internal.RedemptionsDao

// redemptionsDao is the data access object for the table redemptions.
// You can define custom methods on it to extend its functionality as needed.
type redemptionsDao struct {
	internalRedemptionsDao
}

var (
	// Redemptions is a globally accessible object for table redemptions operations.
	Redemptions = redemptionsDao{
		internal.NewRedemptionsDao(),
	}
)

// Add your custom methods and functionality below.
