// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalRewardsDao is an internal type for wrapping the internal DAO implementation.
type internalRewardsDao = *internal.RewardsDao

// rewardsDao is the data access object for the table rewards.
// You can define custom methods on it to extend its functionality as needed.
type rewardsDao struct {
	internalRewardsDao
}

var (
	// Rewards is a globally accessible object for table rewards operations.
	Rewards = rewardsDao{
		internal.NewRewardsDao(),
	}
)

// Add your custom methods and functionality below.
