// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalSessionAnswersDao is an internal type for wrapping the internal DAO implementation.
type internalSessionAnswersDao = *internal.SessionAnswersDao

// sessionAnswersDao is the data access object for the table session_answers.
// You can define custom methods on it to extend its functionality as needed.
type sessionAnswersDao struct {
	internalSessionAnswersDao
}

var (
	// SessionAnswers is a globally accessible object for table session_answers operations.
	SessionAnswers = sessionAnswersDao{
		internal.NewSessionAnswersDao(),
	}
)

// Add your custom methods and functionality below.
