// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// subjectsDao is the data access object for the table subjects.
// You can define custom methods on it to extend its functionality as needed.
type subjectsDao struct {
	*internal.SubjectsDao
}

var (
	// Subjects is a globally accessible object for table subjects operations.
	Subjects = subjectsDao{internal.NewSubjectsDao()}
)

// Add your custom methods and functionality below.
