// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalTasksDao is an internal type for wrapping the internal DAO implementation.
type internalTasksDao = *internal.TasksDao

// tasksDao is the data access object for the table tasks.
// You can define custom methods on it to extend its functionality as needed.
type tasksDao struct {
	internalTasksDao
}

var (
	// Tasks is a globally accessible object for table tasks operations.
	Tasks = tasksDao{
		internal.NewTasksDao(),
	}
)

// Add your custom methods and functionality below.
