// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// internalWordProgressDao is an internal type for wrapping the internal DAO implementation.
type internalWordProgressDao = *internal.WordProgressDao

// wordProgressDao is the data access object for the table word_progress.
// You can define custom methods on it to extend its functionality as needed.
type wordProgressDao struct {
	internalWordProgressDao
}

var (
	// WordProgress is a globally accessible object for table word_progress operations.
	WordProgress = wordProgressDao{
		internal.NewWordProgressDao(),
	}
)

// Add your custom methods and functionality below.
