// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"studyplanet/internal/dao/internal"
)

// wrongQuestionsDao is the data access object for the table wrong_questions.
// You can define custom methods on it to extend its functionality as needed.
type wrongQuestionsDao struct {
	*internal.WrongQuestionsDao
}

var (
	// WrongQuestions is a globally accessible object for table wrong_questions operations.
	WrongQuestions = wrongQuestionsDao{internal.NewWrongQuestionsDao()}
)

// Add your custom methods and functionality below.
