-- 000007 宠物模式：宠物养成 + 投喂 + 好感度（SQLite 方言）

CREATE TABLE IF NOT EXISTS pets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  child_id INTEGER NOT NULL,
  name TEXT NOT NULL DEFAULT '小星球',
  species TEXT NOT NULL DEFAULT 'cat',
  level INTEGER NOT NULL DEFAULT 1,
  exp INTEGER NOT NULL DEFAULT 0,
  hunger INTEGER NOT NULL DEFAULT 80,
  affection INTEGER NOT NULL DEFAULT 20,
  fed_count INTEGER NOT NULL DEFAULT 0,
  last_fed_at TIMESTAMP,
  last_decay_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pets_child ON pets(child_id);
