-- 000006 真人对战（5题×10秒，速度计分）+ 段位系统（SQLite 方言）

CREATE TABLE IF NOT EXISTS battles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room_id TEXT NOT NULL,
  p1_id INTEGER NOT NULL,
  p2_id INTEGER NOT NULL DEFAULT 0,
  subject TEXT NOT NULL DEFAULT 'math',
  grade INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'waiting',
  winner_id INTEGER NOT NULL DEFAULT 0,
  p1_score INTEGER NOT NULL DEFAULT 0,
  p2_score INTEGER NOT NULL DEFAULT 0,
  p1_correct INTEGER NOT NULL DEFAULT 0,
  p2_correct INTEGER NOT NULL DEFAULT 0,
  p1_robot INTEGER NOT NULL DEFAULT 0,
  p2_robot INTEGER NOT NULL DEFAULT 0,
  trophies1 INTEGER NOT NULL DEFAULT 0,
  trophies2 INTEGER NOT NULL DEFAULT 0,
  question_ids TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP NULL
);
CREATE INDEX IF NOT EXISTS idx_battles_p1 ON battles(p1_id);
CREATE INDEX IF NOT EXISTS idx_battles_p2 ON battles(p2_id);
CREATE INDEX IF NOT EXISTS idx_battles_room ON battles(room_id);

CREATE TABLE IF NOT EXISTS battle_scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  child_id INTEGER NOT NULL,
  trophies INTEGER NOT NULL DEFAULT 0,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  draws INTEGER NOT NULL DEFAULT 0,
  battles INTEGER NOT NULL DEFAULT 0,
  best_streak INTEGER NOT NULL DEFAULT 0,
  cur_streak INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_battle_score ON battle_scores(child_id);
